account/urls.py
from django.urls import path
from .views import *

app_name='accounts'

urlpatterns = [
    path('login/', loginPage, name="login"),
    path('logout/', logoutPage, name="logout"),
]

chat/urls.py
from django.urls import path

from . import views

app_name = "chat"

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

core/urls.py
from django.urls import path
from .views import *

app_name="core"


urlpatterns = [
    path("dashboard/", overview, name="overview"),
    path("dashboard/sales", sales, name="sales"),
    path("dashboard/expenses", expenses, name="expenses"),
    path("profile/", profile_view, name="profile"),
    path("task/", task, name="task"),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('horizon-admin/', admin.site.urls),
    path('accounts/', include('account.urls', namespace='accounts')),
    path('', include('staticpages.urls', namespace="pages")),
    path('core/', include('core.urls', namespace="core")),
    path('chat/', include('chat.urls', namespace="chat")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staticpages/urls.py
from django.urls import path
from .views import index

app_name = "pages"

urlpatterns = [
    path('', index, name="home")
]

templates/base.html
{% if user.is_authenticated %}
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css">
        <link rel="stylesheet" href="{% static 'css/base-style.css' %}">
        {% block css %}{% endblock css %}
    </head>

    <body style="background:linear-gradient(to right, purple, #fff)">
        <!--wrapper start-->
        <div class="wrapper">
            <!--header menu start-->
            <div class="header">
                <div class="header-menu">
                    <div class="title">Horizon <span>Dev</span></div>
                    <div class="sidebar-btn">
                        <i class="fas fa-bars"></i>
                    </div>

                    <a href="{% url 'accounts:logout' %}"><i class="fas fa-sign-out-alt"></i>Logout</a>
                </div>
            </div>
            <!--header menu end-->
            <!--sidebar start-->
            <div class="sidebar">
                <div class="sidebar-menu">
                    <center class="profile">
                        <img src="{{user.profile_image.url}}" alt="User Photo">
                        <p>{{user.first_name}}</p>
                    </center>
                    <li class="item" id="dashboard">
                        <a href="#dashboard" class="menu-btn">
                            <i class="fas fa-desktop"></i><span>Dashboard <i class="fas fa-chevron-down drop-down"></i></span>
                        </a>
                        <div class="sub-menu">
                            <a href="{% url 'core:overview' %}"><i class="fas fa-chart-line"></i><span>Overview</span></a>
                            <a href="{% url 'core:sales' %}"><i class="fab fa-salesforce"></i><span>Sales</span></a>
                            <a href="{% url 'core:expenses' %}"><i class="fas fa-money-bill"></i><span>Expanses</span></a>
                        </div>
                    </li>
                    <li class="item" id="profile">
                        <a href="{% url 'core:profile' %}" class="menu-btn">
                            <i class="fas fa-user-circle"></i><span>Profile</span>
                        </a>
                    <li class="item" id="messages">
                        <a href="{% url 'chat:index' %}" class="menu-btn">
                            <i class="fas fa-envelope"></i><span>Chats</span>
                        </a>
                    </li>
                    <li class="item" id="task">
                        <a href="{% url 'core:task' %}" class="menu-btn">
                            <i class="fas fa-tasks"></i><span>Tasks</span>
                        </a>
                    </li>
                </div>
            </div>
            <!--sidebar end-->
            <!--main container start-->
            <div class="main-container">
                {% block content %}
                {% endblock content %}
            </div>
            <!--main container end-->
        </div>
        <!--wrapper end-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8"></script>
        <script src="{% static 'js/sidebar.js' %}" type="text/javascript"></script>
        {% block script %}{% endblock script %}

    </body>
</html>
{% else %}
<meta http-equiv="Refresh" content="0; url='{% url 'pages:home' %}'" />
{% endif %}